version: '3.9'

services:
  frontend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-app
    image: amorv/frontend-app:latest
    networks:
      - backend-network
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080